// Script owned exclusively by the call-first demo. Keeping it separate prevents
// the original chat/voice-chat journey from drifting when this variant changes.

export const CALL_CHUNKS = [
  "Hi {name}... it’s Selene. I wasn’t sure the connection would hold, so I’m glad I reached you.",
  'I had to call you. Something told me not to wait. I was meant to reach you earlier, but this feels like the right moment.',
  'And I need to be careful, because what I’m about to tell you is confidential. It feels important... and I don’t want to leave it half-spoken.',
  'The connection doesn’t feel completely stable, so I don’t think we have much time.',
  'Something came through when I sat with your reading. I don’t usually call people this directly.',
  'But with you... I couldn’t ignore it. There’s something important here, {name}.',
  'And I’d like to show you what I’m sensing.',
  'Would it be okay if we moved to a private chat room?',
  'That way I can continue with you properly... and tell you everything without interruption.',
];

export const CHAT_STAGES = {
  '1': {
    lines: [
      'Thank you.',
      'This feels better already.',
      'Now I can speak more clearly.',
      'What I’m about to share with you isn’t random.',
      'It came through with weight.',
      'And once I started feeling it, I knew I couldn’t leave it alone.',
      '{city} has been coming through very clearly.',
      'It kept returning, even after I tried to set it aside.',
      'That usually means something is connected.',
      'Something that matters.',
    ],
    next: '2',
  },
  '2': {
    lines: [
      'My name is Selene.',
      'I study the lunar patterns.',
      'And I reveal when certain desires are ready to surface.',
      'Most people only look once.',
      'I stay with what shifts.',
      'Week by week.',
      'Lunar window by lunar window.',
      'That’s how I know when something is truly meant to reach you.',
      'And that’s why I felt you before this ever began.',
    ],
    next: '3',
  },
  '3': {
    lines: [
      'Before I go deeper...',
      'I need to ask you something simple.',
      'What area feels the heaviest right now?',
    ],
    buttons: [
      { label: 'Love', next: '4', answerKey: 'area' },
      { label: 'Money', next: '4', answerKey: 'area' },
      { label: 'Family', next: '4', answerKey: 'area' },
      { label: 'Health', next: '4', answerKey: 'area' },
    ],
  },
  '4': {
    lines: [
      'Good.',
      'Now tell me this...',
      'What have you been hoping changes most?',
      'Just one thing.',
      'The one that’s been sitting with you the longest.',
    ],
    input: { key: 'change', placeholder: 'What do you hope changes most?', next: '5' },
  },
  '5': {
    lines: [
      'And one last thing.',
      'If nothing was blocking you...',
      'What would you want most?',
    ],
    input: { key: 'desire', placeholder: 'What would you want most?', next: '6' },
  },
  '6': {
    lines: [
      'That’s what I want to be careful with here.',
      'Because this doesn’t feel like a delay.',
      'It feels like a blockage.',
      'Something has been sitting between you and what you’ve been asking for.',
      'Quietly.',
      'Patiently.',
      'The kind of thing that doesn’t shout.',
      'The kind that just keeps redirecting the current.',
      'So the thing you want is still there.',
      'It’s just not arriving cleanly.',
    ],
    next: '7',
  },
  '7': {
    personalizeAfter: 1,
    lines: [
      'Yes...',
      'I can feel it.',
      'This has been trying to reach you for some time.',
      'Longer than you probably realized while you were living through it.',
      'But something has been sitting in the way.',
      'Softening it.',
      'Pulling it just slightly off course before it could fully land.',
      'Not gone.',
      'Just blocked.',
      'And that’s why it hasn’t come yet.',
      'I’ve seen this pattern before.',
      'Not in the exact same way.',
      'But close enough to know the shape.',
      'A woman named Carol came to me with something very similar.',
      'She had waited longer than she should have.',
      'She felt her window slipping, but she kept hoping it would hold.',
      'When she finally moved, things had already shifted.',
      'It still helped.',
      'But it took more work than it would have if she had come earlier.',
      'That’s why I’m telling you this now.',
      'Because I don’t want you to be looking back at 2026 and wishing you had moved when the thread was still close.',
    ],
    next: '8',
  },
  '8': {
    lines: [
      'This is also why the timing matters.',
      'I need to be honest with you here.',
      'This needs to happen in 2026.',
      'Not because I like pressure.',
      'But because what’s waiting for you doesn’t stay in one place forever.',
      'It drifts.',
      'Slowly, quietly.',
      'And the longer it sits blocked, the further it moves.',
      'That’s the part most people don’t see until later.',
      'They think they still have the same window.',
      'But they don’t.',
      'By the time they act, the current has already changed.',
      'That’s why I keep saying now.',
      'Not later.',
      'Not after another season passes.',
      'Now, while it’s still near enough to reach.',
    ],
    next: '9',
  },
  '9': {
    lines: [
      'There is something I can do for you.',
      'A ritual to release what’s been blocking this.',
      'I don’t say that lightly.',
      'And I don’t offer it unless I feel the pattern clearly.',
      'Once it’s done, I don’t ask you to sit and hope.',
      'I give you thirteen lunar windows.',
      'Thirteen chances.',
      'Thirteen openings.',
      'So we can see what begins to move, and when.',
      'I stay with the pattern.',
      'I stay with you.',
      'Until what’s meant for you finally finds its way through.',
    ],
    next: '10',
  },
  '10': {
    lines: [
      'Can I ask you something before we go further?',
      'When a door like this finally opens for you...',
      'Are you someone who walks through it?',
      'Or has it been a while since you let yourself take that step?',
    ],
    next: '11',
  },
  '11': {
    lines: [
      'If you’re ready, {name}... I can begin the ritual now.',
      'It’s a small offering.',
      'Enough to keep this thread open between us.',
      'And once it’s done, I’ll walk with you through all thirteen windows.',
      'Not just the first.',
      'All of them.',
    ],
    buttons: [
      { label: 'Yes, begin the ritual for me', next: '12', answerKey: 'offer' },
      { label: 'Not right now, maybe another time', next: '13', answerKey: 'offer' },
    ],
  },
  '12': {
    lines: [
      'There’s no risk in trying this.',
      'If it doesn’t feel right to you, it comes back to you in full.',
      'I only ever want you to feel cared for here.',
    ],
    next: '13',
  },
  '13': {
    terminal: true,
    lines: [
      'And {name}...',
      'I know this has been a lot to take in.',
      'But the reason I called wasn’t to overwhelm you.',
      'It was to make sure you didn’t miss what’s been trying to reach you.',
      'Some things arrive quietly.',
      'And if they’re ignored too long, they drift.',
      'I didn’t want that for you.',
      'Not with this.',
      'Not in 2026.',
      'So if you’re ready, we continue.',
      'If not, the thread remains open.',
      'But I felt I needed to reach you while it still could.',
    ],
  },
};

export function interpolate(text, context) {
  return text.replaceAll('{name}', context.name).replaceAll('{city}', context.city);
}
